version: "3.8"
services:
  mongodb:
    image: mongo:4.4
    container_name: healing_blends_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: healing_blends_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./certs/mongod.conf:/etc/mongod.conf
      - ./certs/mongodb.pem:/etc/ssl/mongodb.pem
      - ./certs/ca-cert.pem:/etc/ssl/ca-cert.pem
    command: ["mongod", "--config", "/etc/mongod.conf"]

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healing_blends_node
    ports:
      - "6000:6000"
    environment:
      PORT: 6000
      DATABASE_URL: mongodb://root:example@mongodb:27017/healing_blends_db?authSource=admin&tls=true
      SESSION_SECRET: some_secret
    volumes:
      - ./certs/mongodb.pem:/etc/ssl/mongodb.pem
      - ./certs/ca-cert.pem:/etc/ssl/ca-cert.pem
    depends_on:
      - mongodb

volumes:
  mongo_data:
